name: E2E Testing

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
          browser: chrome
          headless: true
          record: false
        env:
          NOTIFICATIONS_API_URL: ${{ secrets.NOTIFICATIONS_API_URL }}
        # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
